name: EmojiChat
version: 2.0.0
description: Spice up your minecraft with emojis
author: Mithrillia
main: com.mith.EmojiChat.EmojiChat
api-version: 1.18
depend: [UnicodeApi]

commands:
  emojichat:
    description: The main EmojiChat command
    aliases: echat
    usage: /<command>

permissions:
  emojichat.*:
    description: Allows you to use all of the EmojiChat commands and features
    children:
      emojichat.help: true
      emojichat.see: true
      emojichat.list: true
      emojichat.toggle: true
      emojichat.use: true
      emojichat.reload: true
      emojichat.search: true
  emojichat.player:
    description: Allows you to use all of the EmojiChat commands and features for a normal player
    children:
      emojichat.help: true
      emojichat.see: true
      emojichat.list: true
      emojichat.toggle: true
      emojichat.use: true
      emojichat.search: true
  emojichat.help:
    description: Allows you to open the EmojiChat help menu
    default: op
  emojichat.see:
    description: Allows you to see emojis
    default: op
  emojichat.list:
    description: Allows you to list all of the emojis
    default: op
  emojichat.toggle:
    description: Allows you to toggle emoji shortcuts on or off
    default: op
  emojichat.use:
    description: Allows you to use emojis in chat, in commands, and on signs
    default: op
    children:
      emojichat.use.chat: true
      emojichat.use.command: true
      emojichat.use.sign: true
      emojichat.use.anvil: true
  emojichat.use.chat:
    description: Allows you to use emojis in chat
    default: op
  emojichat.use.command:
    description: Allows you to use emojis in commands
    default: op
  emojichat.use.sign:
    description: Allows you to use emojis on signs
    default: op
  emojichat.use.anvil:
    description: Allows you to use emojis in the anvil
    default: op
  emojichat.reload:
    description: Allows you to reload the EmojiChat config
    default: op
  emojichat.serach:
    description: Allows you to use search for emojis
    default: op
  emojichat.browse:
    description: Allows you to use browse the global list of emojis
    default: op
  emojichat.bypass:
    description: Allows you to use dank emojis
    default: op